name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Lint & Build
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Cache NDK
        id: cache-ndk
        uses: actions/cache@v5
        with:
          path: ${{ env.ANDROID_SDK_ROOT }}/ndk/27.0.12077973
          key: ndk-27.0.12077973

      - name: Install NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: sdkmanager "ndk;27.0.12077973"

      - uses: actions/setup-node@v6
        with:
          node-version: '24.5.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:ci

      - name: Verify Android
        run: npm run verify:ci